# Generated by Django 6.0.1 on 2026-01-09 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='店铺的唯一名称', max_length=100, unique=True, verbose_name='店铺名称')),
                ('area', models.DecimalField(decimal_places=2, help_text='店铺面积，单位：平方米', max_digits=6, verbose_name='面积')),
                ('rent', models.DecimalField(decimal_places=2, help_text='每月租金，单位：元', max_digits=8, verbose_name='租金')),
                ('description', models.TextField(blank=True, help_text='店铺的详细描述', null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '店铺',
                'verbose_name_plural': '店铺',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='合同开始日期', verbose_name='开始日期')),
                ('end_date', models.DateField(help_text='合同结束日期', verbose_name='结束日期')),
                ('monthly_rent', models.DecimalField(decimal_places=2, help_text='每月租金，单位：元', max_digits=8, verbose_name='月租金')),
                ('deposit', models.DecimalField(decimal_places=2, default=0, help_text='押金，单位：元', max_digits=8, verbose_name='押金')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('ACTIVE', '生效'), ('EXPIRED', '过期'), ('TERMINATED', '终止')], default='DRAFT', help_text='合同状态', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('shop', models.ForeignKey(help_text='关联的店铺', on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='store.shop', verbose_name='店铺')),
            ],
            options={
                'verbose_name': '合同',
                'verbose_name_plural': '合同',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='contract_end_date_gt_start_date'), models.CheckConstraint(condition=models.Q(('monthly_rent__gt', 0)), name='contract_monthly_rent_gt_0'), models.CheckConstraint(condition=models.Q(('deposit__gte', 0)), name='contract_deposit_gte_0')],
            },
        ),
    ]
