# Generated by Django 6.0.1 on 2026-01-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='逻辑删除标记', verbose_name='是否删除'),
        ),
    ]
