# Generated by Django 6.0.1 on 2026-01-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_shop_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='business_type',
            field=models.CharField(choices=[('RETAIL', '零售'), ('FOOD', '餐饮'), ('ENTERTAINMENT', '娱乐'), ('SERVICE', '服务'), ('OTHER', '其他')], default='OTHER', help_text='店铺的业态类型', max_length=20, verbose_name='业态类型'),
        ),
        migrations.AddField(
            model_name='shop',
            name='contact_person',
            field=models.CharField(blank=True, help_text='店铺联系人姓名', max_length=50, null=True, verbose_name='联系人'),
        ),
        migrations.AddField(
            model_name='shop',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='店铺联系人电话', max_length=20, null=True, verbose_name='联系方式'),
        ),
        migrations.AddField(
            model_name='shop',
            name='entry_date',
            field=models.DateField(blank=True, help_text='店铺入驻商场的日期', null=True, verbose_name='入驻日期'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='area',
            field=models.DecimalField(decimal_places=2, help_text='店铺面积，单位：平方米', max_digits=6, verbose_name='经营面积'),
        ),
    ]
