# Generated by Django 6.0.1 on 2026-01-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_shop_business_type_shop_contact_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='payment_cycle',
            field=models.CharField(choices=[('MONTHLY', '月付'), ('QUARTERLY', '季付'), ('SEMIANNUALLY', '半年付'), ('ANNUALLY', '年付')], default='MONTHLY', help_text='租金缴费周期', max_length=20, verbose_name='缴费周期'),
        ),
    ]
