# Generated by Django 6.0.1 on 2026-01-16 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_contract_payment_cycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='review_comment',
            field=models.TextField(blank=True, help_text='审核人的意见备注', null=True, verbose_name='审核意见'),
        ),
        migrations.AddField(
            model_name='contract',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='合同审核的时间', null=True, verbose_name='审核时间'),
        ),
        migrations.AddField(
            model_name='contract',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='审核该合同的管理员', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_contracts', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('DRAFT', '草稿'), ('PENDING_REVIEW', '待审核'), ('APPROVED', '已批准'), ('REJECTED', '已拒绝'), ('ACTIVE', '生效'), ('EXPIRED', '过期'), ('TERMINATED', '终止')], default='DRAFT', help_text='合同状态', max_length=20, verbose_name='状态'),
        ),
    ]
