# Generated by Django 5.2.10 on 2026-02-07 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_shop_contract_tenant_orgunit'),
        ('tenants', '0003_rename_tenants_org_tenant__c22241_idx_tenants_org_tenant__614b8d_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contract',
            new_name='store_contr_tenant__c6abb3_idx',
            old_name='store_contract_tenant__d3a2b1_idx',
        ),
        migrations.RenameIndex(
            model_name='contract',
            new_name='store_contr_tenant__4255fd_idx',
            old_name='store_contract_tenant__09f918_idx',
        ),
        migrations.RenameIndex(
            model_name='shop',
            new_name='store_shop_tenant__053ad4_idx',
            old_name='store_shop_tenant__289da5_idx',
        ),
        migrations.RenameIndex(
            model_name='shop',
            new_name='store_shop_tenant__e6fae0_idx',
            old_name='store_shop_tenant__e31dd4_idx',
        ),
        migrations.AddField(
            model_name='shop',
            name='address',
            field=models.CharField(blank=True, help_text='详细地址或楼层位置', max_length=255, null=True, verbose_name='店铺地址'),
        ),
        migrations.AddField(
            model_name='shop',
            name='code',
            field=models.CharField(blank=True, help_text='外部或业务系统的店铺编号，用于去重匹配', max_length=50, null=True, verbose_name='店铺编号'),
        ),
        migrations.AddField(
            model_name='shop',
            name='mall_name',
            field=models.CharField(blank=True, help_text='所在商场、园区或区域，用于去重匹配与展示', max_length=120, null=True, verbose_name='商场/园区/区域'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='tenant',
            field=models.ForeignKey(help_text='合同所属的租户/商场', on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='tenants.tenant', verbose_name='租户'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(help_text='店铺名称（租户内唯一）', max_length=100, verbose_name='店铺名称'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='org_unit',
            field=models.ForeignKey(blank=True, help_text='店铺所属组织层级', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='tenants.orgunit', verbose_name='组织单元'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='tenant',
            field=models.ForeignKey(help_text='店铺所属的租户/商场', on_delete=django.db.models.deletion.PROTECT, related_name='shops', to='tenants.tenant', verbose_name='租户'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['tenant', 'code'], name='store_shop_tenant__a9ff6f_idx'),
        ),
        migrations.AddConstraint(
            model_name='shop',
            constraint=models.UniqueConstraint(condition=models.Q(('code__isnull', False)), fields=('tenant', 'code'), name='shop_unique_code_per_tenant'),
        ),
    ]
