# Generated by Django 5.2.10 on 2026-02-10 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_store_contract_tenant__d3a2b1_idx_store_contr_tenant__c6abb3_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='合同归档时间', null=True, verbose_name='归档时间'),
        ),
        migrations.AddField(
            model_name='contract',
            name='archived_by',
            field=models.ForeignKey(blank=True, help_text='执行归档操作的用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_contracts', to=settings.AUTH_USER_MODEL, verbose_name='归档人'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_no',
            field=models.CharField(blank=True, db_index=True, help_text='合同业务编号（同租户内唯一）', max_length=64, null=True, verbose_name='合同编号'),
        ),
        migrations.AddField(
            model_name='contract',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='合同是否归档，归档后默认不在列表展示', verbose_name='是否归档'),
        ),
    ]
