# Generated by Django 5.2.10 on 2026-02-10 08:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_contract_archived_at_contract_archived_by_and_more'),
        ('tenants', '0003_rename_tenants_org_tenant__c22241_idx_tenants_org_tenant__614b8d_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(condition=models.Q(('contract_no__isnull', False)), fields=('tenant', 'contract_no'), name='contract_unique_no_per_tenant'),
        ),
    ]
