# Generated by Django 5.2.10 on 2026-02-10 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_contract_contract_unique_no_per_tenant'),
        ('tenants', '0003_rename_tenants_org_tenant__c22241_idx_tenants_org_tenant__614b8d_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='年份')),
                ('last_seq', models.PositiveIntegerField(default=0, verbose_name='最新序号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_number_sequences', to='tenants.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '合同编号序列',
                'verbose_name_plural': '合同编号序列',
                'indexes': [models.Index(fields=['tenant', 'year'], name='store_contr_tenant__ba1792_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'year'), name='contract_no_seq_unique_tenant_year')],
            },
        ),
    ]
