# Generated by Django 5.2.10 on 2026-02-12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_contractnumbersequence"),
        ("tenants", "0003_rename_tenants_org_tenant__c22241_idx_tenants_org_tenant__614b8d_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalFlowConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "target_type",
                    models.CharField(
                        choices=[("CONTRACT", "Contract")],
                        db_index=True,
                        default="CONTRACT",
                        max_length=32,
                        verbose_name="Target Type",
                    ),
                ),
                ("node_name", models.CharField(max_length=64, verbose_name="Node Name")),
                ("order_no", models.PositiveSmallIntegerField(default=1, verbose_name="Order No")),
                (
                    "approver_role",
                    models.CharField(
                        blank=True,
                        help_text="Optional role: ADMIN / MANAGEMENT / OPERATION",
                        max_length=32,
                        null=True,
                        verbose_name="Approver Role",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True, verbose_name="Is Active")),
                ("sla_hours", models.PositiveIntegerField(blank=True, null=True, verbose_name="SLA Hours")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_flow_config_nodes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approver",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_flow_configs",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Approval Flow Config",
                "verbose_name_plural": "Approval Flow Config",
                "ordering": ["target_type", "order_no", "id"],
                "indexes": [
                    models.Index(fields=["tenant", "target_type", "is_active"], name="store_appro_tenant__de9d57_idx"),
                    models.Index(fields=["tenant", "approver_role"], name="store_appro_tenant__8a4f8a_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "target_type", "order_no"),
                        name="approval_flow_unique_order_per_target",
                    ),
                ],
            },
        ),
    ]
