# Generated by Django 5.2.10 on 2026-02-12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_approvalflowconfig"),
        ("tenants", "0003_rename_tenants_org_tenant__c22241_idx_tenants_org_tenant__614b8d_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("round_no", models.PositiveIntegerField(default=1, verbose_name="Round No")),
                ("order_no", models.PositiveSmallIntegerField(default=1, verbose_name="Order No")),
                ("node_name", models.CharField(max_length=64, verbose_name="Node Name")),
                ("approver_role", models.CharField(blank=True, max_length=32, null=True, verbose_name="Approver Role")),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("APPROVED", "Approved"), ("REJECTED", "Rejected"), ("SKIPPED", "Skipped")],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True, verbose_name="Comment")),
                ("sla_due_at", models.DateTimeField(blank=True, null=True, verbose_name="SLA Due At")),
                ("acted_at", models.DateTimeField(blank=True, null=True, verbose_name="Acted At")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "acted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handled_approval_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Acted By",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_approval_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assigned To",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_tasks",
                        to="store.contract",
                        verbose_name="Contract",
                    ),
                ),
                (
                    "flow_config",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_tasks",
                        to="store.approvalflowconfig",
                        verbose_name="Flow Config",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_tasks",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Approval Task",
                "verbose_name_plural": "Approval Task",
                "ordering": ["contract_id", "-round_no", "order_no", "id"],
                "indexes": [
                    models.Index(fields=["tenant", "contract", "status"], name="store_appro_tenant__3dcfe1_idx"),
                    models.Index(fields=["tenant", "assigned_to", "status"], name="store_appro_tenant__8603ce_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("contract", "round_no", "order_no"),
                        name="approval_task_unique_contract_round_order",
                    ),
                ],
            },
        ),
    ]
