# Generated by Django 5.2.10 on 2026-02-12 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_approvaltask"),
        ("tenants", "0003_rename_tenants_org_tenant__c22241_idx_tenants_org_tenant__614b8d_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("item_type", models.CharField(choices=[("RENT", "租金"), ("PROPERTY_FEE", "物业费"), ("DEPOSIT", "押金"), ("REVENUE_SHARE", "分成"), ("OTHER", "其他")], db_index=True, default="RENT", max_length=32, verbose_name="费用项类型")),
                ("calc_type", models.CharField(choices=[("FIXED", "固定值"), ("STEP", "阶梯"), ("ESCALATION", "递增"), ("PERCENTAGE", "比例")], default="FIXED", max_length=16, verbose_name="计费方式")),
                ("amount", models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="基础金额")),
                ("rate", models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name="比例/递增率")),
                ("tax_rate", models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name="税率")),
                ("currency", models.CharField(default="CNY", max_length=8, verbose_name="币种")),
                ("period_start", models.DateField(blank=True, null=True, verbose_name="费用项起始日期")),
                ("period_end", models.DateField(blank=True, null=True, verbose_name="费用项结束日期")),
                ("payment_cycle", models.CharField(choices=[("MONTHLY", "月付"), ("QUARTERLY", "季付"), ("SEMIANNUALLY", "半年付"), ("ANNUALLY", "年付"), ("ONE_TIME", "一次性")], default="MONTHLY", max_length=20, verbose_name="缴费周期")),
                ("free_rent_from", models.DateField(blank=True, null=True, verbose_name="免租开始")),
                ("free_rent_to", models.DateField(blank=True, null=True, verbose_name="免租结束")),
                ("sequence", models.PositiveSmallIntegerField(default=1, verbose_name="显示顺序")),
                ("status", models.CharField(choices=[("ACTIVE", "启用"), ("INACTIVE", "停用")], db_index=True, default="ACTIVE", max_length=16, verbose_name="状态")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("contract", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="contract_items", to="store.contract", verbose_name="合同")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="contract_items", to="tenants.tenant", verbose_name="租户")),
            ],
            options={
                "verbose_name": "合同费用项",
                "verbose_name_plural": "合同费用项",
                "ordering": ["contract_id", "sequence", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="contractitem",
            index=models.Index(fields=["tenant", "contract", "status"], name="store_contr_tenant__0cab8b_idx"),
        ),
        migrations.AddIndex(
            model_name="contractitem",
            index=models.Index(fields=["tenant", "item_type"], name="store_contr_tenant__8ff141_idx"),
        ),
        migrations.AddConstraint(
            model_name="contractitem",
            constraint=models.CheckConstraint(condition=models.Q(("amount__gte", 0)), name="contract_item_amount_gte_0"),
        ),
        migrations.AddConstraint(
            model_name="contractitem",
            constraint=models.CheckConstraint(condition=models.Q(("period_end__isnull", True), ("period_start__isnull", True), ("period_end__gte", models.F("period_start")), _connector="OR"), name="contract_item_period_valid"),
        ),
        migrations.AddConstraint(
            model_name="contractitem",
            constraint=models.UniqueConstraint(fields=("contract", "sequence"), name="contract_item_unique_sequence_per_contract"),
        ),
    ]
