# Generated by Django 5.2.10 on 2026-02-12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_contractitem_alter_approvalflowconfig_options_and_more"),
        ("tenants", "0003_rename_tenants_org_tenant__c22241_idx_tenants_org_tenant__614b8d_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("attachment_type", models.CharField(choices=[("MAIN", "主合同"), ("SUPPLEMENT", "补充协议"), ("ANNEX", "附件"), ("QUALIFICATION", "资质文件")], db_index=True, default="MAIN", max_length=20, verbose_name="附件类型")),
                ("file", models.FileField(upload_to="contract_attachments/%Y/%m/", verbose_name="文件")),
                ("original_name", models.CharField(max_length=255, verbose_name="原始文件名")),
                ("mime_type", models.CharField(blank=True, max_length=100, null=True, verbose_name="文件类型")),
                ("file_size", models.PositiveIntegerField(default=0, verbose_name="文件大小")),
                ("file_hash", models.CharField(db_index=True, max_length=64, verbose_name="文件哈希")),
                ("version_no", models.PositiveIntegerField(default=1, verbose_name="版本号")),
                ("is_current", models.BooleanField(db_index=True, default=True, verbose_name="是否当前版本")),
                ("remark", models.TextField(blank=True, null=True, verbose_name="备注")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="上传时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("contract", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="attachments", to="store.contract", verbose_name="合同")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="contract_attachments", to="tenants.tenant", verbose_name="租户")),
                ("uploaded_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="uploaded_contract_attachments", to=settings.AUTH_USER_MODEL, verbose_name="上传人")),
            ],
            options={
                "verbose_name": "合同附件",
                "verbose_name_plural": "合同附件",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ContractSignature",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("party_type", models.CharField(choices=[("LANDLORD", "甲方"), ("TENANT", "乙方"), ("WITNESS", "见证方"), ("OTHER", "其他")], db_index=True, default="TENANT", max_length=20, verbose_name="签署方")),
                ("signer_name", models.CharField(max_length=100, verbose_name="签署人")),
                ("signer_title", models.CharField(blank=True, max_length=100, null=True, verbose_name="职务")),
                ("sign_method", models.CharField(choices=[("ONLINE", "电子签"), ("OFFLINE", "线下签")], default="OFFLINE", max_length=20, verbose_name="签署方式")),
                ("signed_at", models.DateTimeField(db_index=True, verbose_name="签署时间")),
                ("evidence_hash", models.CharField(blank=True, max_length=64, null=True, verbose_name="签署证据哈希")),
                ("comment", models.TextField(blank=True, null=True, verbose_name="备注")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="登记时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("attachment", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="signature_records", to="store.contractattachment", verbose_name="关联签署文件")),
                ("contract", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="signatures", to="store.contract", verbose_name="合同")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_contract_signatures", to=settings.AUTH_USER_MODEL, verbose_name="登记人")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="contract_signatures", to="tenants.tenant", verbose_name="租户")),
            ],
            options={
                "verbose_name": "合同签署",
                "verbose_name_plural": "合同签署",
                "ordering": ["-signed_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="contractattachment",
            index=models.Index(fields=["tenant", "contract", "attachment_type"], name="store_contr_tenant__b1a2_idx"),
        ),
        migrations.AddIndex(
            model_name="contractattachment",
            index=models.Index(fields=["tenant", "file_hash"], name="store_contr_tenant__70fd_idx"),
        ),
        migrations.AddConstraint(
            model_name="contractattachment",
            constraint=models.UniqueConstraint(fields=("contract", "attachment_type", "version_no"), name="contract_attachment_unique_version"),
        ),
        migrations.AddIndex(
            model_name="contractsignature",
            index=models.Index(fields=["tenant", "contract", "signed_at"], name="store_contr_tenant__6b83_idx"),
        ),
        migrations.AddIndex(
            model_name="contractsignature",
            index=models.Index(fields=["tenant", "party_type"], name="store_contr_tenant__a7e0_idx"),
        ),
    ]
