# Generated by Django 6.0.1 on 2026-01-09 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='金额')),
                ('billing_period_start', models.DateField(db_index=True, verbose_name='账单周期开始日期')),
                ('billing_period_end', models.DateField(db_index=True, verbose_name='账单周期结束日期')),
                ('status', models.CharField(choices=[('UNPAID', '未支付'), ('PAID', '已支付'), ('VOID', '已作废')], db_index=True, default='UNPAID', max_length=20, verbose_name='账单状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_records', to='store.contract', verbose_name='关联合同')),
            ],
            options={
                'verbose_name': '财务记录',
                'verbose_name_plural': '财务记录',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('billing_period_end__gt', models.F('billing_period_start'))), name='finance_record_period_end_gt_start')],
            },
        ),
    ]
