# Generated by Django 6.0.1 on 2026-01-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financerecord',
            name='fee_type',
            field=models.CharField(choices=[('RENT', '租金'), ('PROPERTY_FEE', '物业费'), ('UTILITY_FEE', '水电费'), ('OTHER', '其他费用')], db_index=True, default='RENT', max_length=20, verbose_name='费用类型'),
        ),
        migrations.AddField(
            model_name='financerecord',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='缴费时间'),
        ),
        migrations.AddField(
            model_name='financerecord',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('WECHAT', '微信支付'), ('ALIPAY', '支付宝'), ('BANK_TRANSFER', '银行转账'), ('CASH', '现金')], max_length=20, null=True, verbose_name='缴费方式'),
        ),
        migrations.AddField(
            model_name='financerecord',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='交易单号'),
        ),
    ]
