# Generated by Django 6.0.1 on 2026-01-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_financerecord_fee_type_financerecord_paid_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financerecord',
            name='reminder_sent',
            field=models.BooleanField(default=False, help_text='用于追踪是否已发送支付提醒，避免重复提醒', verbose_name='是否已发送提醒'),
        ),
    ]
