# Generated by Django 5.2.10 on 2026-02-12 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_financerecord_tenant"),
        ("store", "0013_contractitem_alter_approvalflowconfig_options_and_more"),
        ("tenants", "0003_rename_tenants_org_tenant__c22241_idx_tenants_org_tenant__614b8d_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingSchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("period_start", models.DateField(db_index=True, verbose_name="账期开始")),
                ("period_end", models.DateField(db_index=True, verbose_name="账期结束")),
                ("due_date", models.DateField(db_index=True, verbose_name="应收日期")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="计划金额")),
                ("status", models.CharField(choices=[("PLANNED", "待出账"), ("ISSUED", "已出账"), ("PARTIAL", "部分支付"), ("PAID", "已支付"), ("VOID", "作废"), ("OVERDUE", "逾期")], db_index=True, default="PLANNED", max_length=16, verbose_name="计划状态")),
                ("source_version", models.PositiveIntegerField(default=1, verbose_name="来源合同版本")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("contract", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="billing_schedules", to="store.contract", verbose_name="合同")),
                ("contract_item", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="billing_schedules", to="store.contractitem", verbose_name="合同费用项")),
                ("finance_record", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="billing_schedule", to="finance.financerecord", verbose_name="生成财务记录")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="billing_schedules", to="tenants.tenant", verbose_name="租户")),
            ],
            options={
                "verbose_name": "账单计划",
                "verbose_name_plural": "账单计划",
                "ordering": ["contract_id", "period_start", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="billingschedule",
            index=models.Index(fields=["tenant", "contract", "status"], name="finance_bil_tenant__c21d96_idx"),
        ),
        migrations.AddIndex(
            model_name="billingschedule",
            index=models.Index(fields=["tenant", "due_date"], name="finance_bil_tenant__7ab237_idx"),
        ),
        migrations.AddConstraint(
            model_name="billingschedule",
            constraint=models.CheckConstraint(condition=models.Q(("period_end__gte", models.F("period_start"))), name="billing_schedule_period_end_gte_start"),
        ),
        migrations.AddConstraint(
            model_name="billingschedule",
            constraint=models.CheckConstraint(condition=models.Q(("amount__gte", 0)), name="billing_schedule_amount_gte_0"),
        ),
        migrations.AddConstraint(
            model_name="billingschedule",
            constraint=models.UniqueConstraint(fields=("contract", "contract_item", "period_start", "period_end", "source_version"), name="billing_schedule_unique_period_per_item_version"),
        ),
    ]
