# Generated by Django 6.0.1 on 2026-01-16 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_name', models.CharField(help_text='备份文件名称', max_length=255)),
                ('backup_type', models.CharField(choices=[('FULL', '全量备份'), ('INCREMENTAL', '增量备份')], default='FULL', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', '待处理'), ('RUNNING', '进行中'), ('SUCCESS', '成功'), ('FAILED', '失败')], default='PENDING', max_length=20)),
                ('data_types', models.JSONField(default=list, help_text='备份包含的数据类型列表')),
                ('file_path', models.CharField(help_text='备份文件存储路径', max_length=500)),
                ('file_size', models.BigIntegerField(default=0, help_text='备份文件大小（字节）')),
                ('file_hash', models.CharField(blank=True, help_text='备份文件SHA256哈希值', max_length=64)),
                ('is_encrypted', models.BooleanField(default=False, help_text='是否加密存储')),
                ('encryption_key_id', models.CharField(blank=True, help_text='加密密钥ID', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='备份创建时间')),
                ('backup_start_time', models.DateTimeField(blank=True, help_text='备份开始时间', null=True)),
                ('backup_end_time', models.DateTimeField(blank=True, help_text='备份结束时间', null=True)),
                ('is_automatic', models.BooleanField(default=True, help_text='是否自动备份')),
                ('recovery_records', models.IntegerField(default=0, help_text='已使用该备份恢复的次数')),
                ('last_recovered_at', models.DateTimeField(blank=True, help_text='最后一次恢复时间', null=True)),
                ('description', models.TextField(blank=True, help_text='备份说明或备注')),
                ('error_message', models.TextField(blank=True, help_text='备份失败时的错误信息')),
                ('created_by', models.ForeignKey(help_text='创建备份的管理员', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '备份记录',
                'verbose_name_plural': '备份记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('BACKUP', '执行备份'), ('RESTORE', '执行恢复'), ('VERIFY', '验证备份'), ('DELETE', '删除备份'), ('DOWNLOAD', '下载备份')], help_text='操作类型', max_length=20)),
                ('log_level', models.CharField(choices=[('INFO', '信息'), ('WARNING', '警告'), ('ERROR', '错误'), ('SUCCESS', '成功')], default='INFO', max_length=20)),
                ('message', models.TextField(help_text='日志消息')),
                ('details', models.JSONField(blank=True, default=dict, help_text='操作详细信息')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operated_by', models.ForeignKey(help_text='操作者', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('backup_record', models.ForeignKey(help_text='关联的备份记录', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='backup.backuprecord')),
            ],
            options={
                'verbose_name': '备份日志',
                'verbose_name_plural': '备份日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='backuprecord',
            index=models.Index(fields=['-created_at'], name='backup_back_created_938504_idx'),
        ),
        migrations.AddIndex(
            model_name='backuprecord',
            index=models.Index(fields=['status'], name='backup_back_status_e782d3_idx'),
        ),
        migrations.AddIndex(
            model_name='backuprecord',
            index=models.Index(fields=['backup_type'], name='backup_back_backup__b8d77c_idx'),
        ),
        migrations.AddIndex(
            model_name='backuplog',
            index=models.Index(fields=['-created_at'], name='backup_back_created_e909d4_idx'),
        ),
        migrations.AddIndex(
            model_name='backuplog',
            index=models.Index(fields=['operation'], name='backup_back_operati_314d07_idx'),
        ),
    ]
