# Generated by Django 5.2.10 on 2026-02-07 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_create_default_tenant'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='orgunit',
            new_name='tenants_org_tenant__614b8d_idx',
            old_name='tenants_org_tenant__c22241_idx',
        ),
        migrations.RenameIndex(
            model_name='orgunit',
            new_name='tenants_org_tenant__55dac4_idx',
            old_name='tenants_org_tenant__b7fe7f_idx',
        ),
    ]
