"""
Django settings for store_management project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import logging

# ============================================
# 环境变量配置（优先）
# ============================================
try:
    from decouple import config, Csv
    DEBUG = config('DEBUG', default=True, cast=bool)
    SECRET_KEY = config('SECRET_KEY', default='django-insecure-placeholder-secret-key')
    ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1,testserver', cast=Csv())
except ImportError:
    # 如果 decouple 未安装，使用默认值
    DEBUG = True
    SECRET_KEY = 'django-insecure-placeholder-secret-key'
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'testserver']

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-placeholder-secret-key'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'drf_spectacular',
    'apps.core',
    'apps.store',
    'apps.finance',
    'apps.dashboard',
    'apps.operations',
    'apps.communication',
    'apps.query',
    'apps.reports',
    'apps.user_management',
    'apps.backup',
    'apps.notification',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'apps.core.middleware.ExceptionMiddleware',  # 添加异常处理中间件
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'builtins': [
                'apps.core.templatetags.custom_filters',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login URL
LOGIN_URL = '/core/login/'

# 备份配置
BACKUP_DIR = BASE_DIR / 'backups'  # 备份文件存储目录
BACKUP_COMPRESSION = True  # 是否压缩备份文件
BACKUP_ENCRYPTION = False  # 是否加密备份文件

# ============================================
# Celery 配置
# ============================================
CELERY_BROKER_URL = 'redis://localhost:6379/0'  # 任务队列代理（可选，默认使用内存）
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'  # 结果后端（可选）
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Shanghai'
CELERY_ENABLE_UTC = True
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30分钟硬限制
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25分钟软限制
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000
BACKUP_RETENTION_DAYS = 30  # 备份保留天数，超过此天数的备份会被自动删除

# ============================================
# CORS 跨域配置
# ============================================
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",      # Vue/React 开发服务器
    "http://localhost:8080",      # 备用前端服务器
    "http://localhost:5173",      # Vite 开发服务器
    "http://127.0.0.1:3000",
    "http://127.0.0.1:8080",
    "http://127.0.0.1:5173",
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# ============================================
# REST Framework 配置
# ============================================
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'EXCEPTION_HANDLER': 'apps.core.middleware.custom_exception_handler',
}

# ============================================
# Spectacular API 文档配置
# ============================================
SPECTACULAR_SETTINGS = {
    'TITLE': '商场店铺智能运营管理系统 API',
    'DESCRIPTION': '完整的 RESTful API 文档',
    'VERSION': '1.0.0',
    'SERVE_PERMISSIONS': ['rest_framework.permissions.AllowAny'],
    'SERVERS': [
        {'url': 'http://localhost:8000', 'description': '本地开发服务器'},
        {'url': 'https://api.example.com', 'description': '生产服务器'},
    ],
    'CONTACT': {
        'name': '技术支持',
        'email': 'support@example.com',
    },
}

# ============================================
# 日志配置
# ============================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {name} {funcName}:{lineno} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '[{levelname}] {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'level': 'DEBUG',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 5,
            'level': 'INFO',
            'formatter': 'verbose',
        },
        'error_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'error.log',
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 5,
            'level': 'ERROR',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'apps': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'celery': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# 创建日志目录
os.makedirs(BASE_DIR / 'logs', exist_ok=True)

# ============================================
# 安全配置（生产环境优化）
# ============================================

# 安全中间件配置
if not DEBUG:
    # HTTPS 相关
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # HSTS (HTTP Strict Transport Security)
    SECURE_HSTS_SECONDS = 31536000  # 1 年
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # 内容安全策略
    SECURE_CONTENT_SECURITY_POLICY = {
        'DEFAULT_SRC': ("'self'",),
        'SCRIPT_SRC': ("'self'", "'unsafe-inline'"),  # 开发时可能需要 unsafe-inline，生产应移除
        'STYLE_SRC': ("'self'", "'unsafe-inline'"),
        'IMG_SRC': ("'self'", "data:", "https:"),
        'FONT_SRC': ("'self'", "data:"),
        'CONNECT_SRC': ("'self'",),
        'FRAME_ANCESTORS': ("'none'",),
    }
    
    # X-Frame-Options: DENY 防止 clickjacking 攻击
    X_FRAME_OPTIONS = 'DENY'
    
    # 浏览器 XSS 防护
    SECURE_BROWSER_XSS_FILTER = True
    
    # 防止内容类型嗅探
    SECURE_CONTENT_TYPE_NOSNIFF = True

# Session 安全配置
SESSION_COOKIE_HTTPONLY = True  # 防止 JavaScript 访问 session cookie
SESSION_COOKIE_SAMESITE = 'Strict'  # 防止 CSRF 攻击
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # 生产环境可能需要
SESSION_COOKIE_AGE = 3600  # 1 小时（开发时），生产可改为 86400（24小时）

# CSRF 保护
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Strict'
CSRF_FAILURE_VIEW = 'apps.core.views.csrf_failure'  # 自定义 CSRF 失败视图

# 密码验证政策
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,  # 最少 8 个字符
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# 重定向配置（防止 Open Redirect 攻击）
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',
    'http://localhost:8080',
    'http://localhost:5173',
    'https://yourdomain.com',
]

# 安全中间件
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')  # 如果使用反向代理

# 防止缓存敏感数据
SECURE_HSTS_INCLUDE_SUBDOMAINS = True

# ============================================
# 管理员和用户界面安全
# ============================================

# Django Admin 安全
ADMIN_URL = 'admin/'  # 不使用默认的 /admin/
ADMIN_USER_CHANGE_PASSWORD_REQUIRED = True  # 强制首次密码更改

# ============================================
# 备份和数据保护
# ============================================

# 备份保留策略
BACKUP_RETENTION_DAYS = config('BACKUP_RETENTION_DAYS', default=30, cast=int)
BACKUP_COMPRESSION = config('BACKUP_COMPRESSION', default=True, cast=bool)
BACKUP_ENCRYPTION = config('BACKUP_ENCRYPTION', default=False, cast=bool)

# ============================================
# 错误处理和日志记录
# ============================================

# 注：错误处理程序在 config/urls.py 中配置

# ============================================
# Sentry 错误追踪配置
# ============================================

SENTRY_DSN = config('SENTRY_DSN', default=None)
SENTRY_ENABLED = SENTRY_DSN is not None and not DEBUG

if SENTRY_ENABLED:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    from sentry_sdk.integrations.logging import LoggingIntegration
    from sentry_sdk.integrations.celery import CeleryIntegration
    from sentry_sdk.integrations.redis import RedisIntegration
    
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[
            DjangoIntegration(),
            LoggingIntegration(
                level=logging.INFO,        # 捕获 INFO 级别及以上的日志
                event_level=logging.ERROR  # 仅报告 ERROR 级别的日志事件
            ),
            CeleryIntegration(),
            RedisIntegration(),
        ],
        
        # 性能监控配置
        traces_sample_rate=config('SENTRY_TRACES_SAMPLE_RATE', default=0.1, cast=float),
        
        # 错误采样配置
        sample_rate=config('SENTRY_SAMPLE_RATE', default=1.0, cast=float),
        
        # 环境标识
        environment=config('ENVIRONMENT', default='production'),
        
        # 发送内容配置
        attach_stacktrace=True,  # 附加堆栈跟踪到消息事件
        include_local_variables=False,  # 不在生产环境暴露本地变量
        
        # 排除不需要报告的错误
        ignore_errors=[
            'KeyboardInterrupt',
            'SystemExit',
            'django.http.response.Http404',
        ],
        
        # 自定义事件处理器
        before_send=lambda event, hint: event if not DEBUG else None,
        
        # 额外的上下文配置
        release=config('RELEASE', default=None),
        max_breadcrumbs=50,
        with_locals=False,
    )
    
    # 在日志中标记已初始化
    logging.getLogger(__name__).info(
        f'Sentry 已初始化，DSN: {SENTRY_DSN[:50]}..., 环境: {config("ENVIRONMENT", default="production")}'
    )
