"""
Django settings for store_management project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import logging

# ============================================
# 环境与安全配置
# ============================================
from django.core.exceptions import ImproperlyConfigured
# Note: Previously DEBUG/SECRET_KEY/ALLOWED_HOSTS were defined twice (config() then hardcoded).
# This block enforces a single source of truth.

def _parse_bool(value, default=False):
    if value is None:
        return default
    return str(value).strip().lower() in {'1', 'true', 'yes', 'on'}


def _parse_hosts(value):
    if value is None:
        return []
    if isinstance(value, (list, tuple)):
        return [str(item).strip() for item in value if str(item).strip()]
    return [item.strip() for item in str(value).split(',') if item.strip()]


try:
    from decouple import config

    def _env(name, default=None, cast=None):
        if cast is None:
            return config(name, default=default)
        return config(name, default=default, cast=cast)
except ImportError:
    def _env(name, default=None, cast=None):
        value = os.environ.get(name, default)
        if cast is bool:
            return _parse_bool(value, default=bool(default))
        return value
    config = _env

# ENV / ENVIRONMENT 作为环境标识
ENV = _env('ENV', default=_env('ENVIRONMENT', default='development'))
ENV = str(ENV).strip().lower()

# DEBUG: 支持 DJANGO_DEBUG/DEBUG，生产强制 False
DEBUG = _env('DJANGO_DEBUG', default=_env('DEBUG', default=(ENV != 'production')), cast=bool)
if ENV == 'production':
    DEBUG = False

# SECRET_KEY: 从环境变量读取
SECRET_KEY = _env('DJANGO_SECRET_KEY', default=_env('SECRET_KEY', default=None))
if not SECRET_KEY:
    if ENV == 'production' or not DEBUG:
        raise ImproperlyConfigured(
            'SECRET_KEY is required in production or when DEBUG is False.'
        )
    SECRET_KEY = 'django-insecure-development-placeholder'

# ALLOWED_HOSTS: 从环境变量读取
ALLOWED_HOSTS_RAW = _env('DJANGO_ALLOWED_HOSTS', default=_env('ALLOWED_HOSTS', default=None))
ALLOWED_HOSTS = _parse_hosts(ALLOWED_HOSTS_RAW)
if not ALLOWED_HOSTS:
    if ENV == 'production' or not DEBUG:
        raise ImproperlyConfigured(
            'ALLOWED_HOSTS is required in production or when DEBUG is False.'
        )
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]']

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-placeholder-secret-key'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django_prometheus',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'drf_spectacular',
    'apps.audit',
    'apps.core',
    'apps.tenants',
    'apps.store',
    'apps.finance',
    'apps.dashboard',
    'apps.operations',
    'apps.communication',
    'apps.query',
    'apps.reports',
    'apps.user_management',
    'apps.backup',
    'apps.notification',
    'apps.data_governance',
]

MIDDLEWARE = [
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'apps.tenants.middleware.TenantMiddleware',
    'apps.audit.middleware.AuditRequestMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'apps.core.middleware.MetricsAccessMiddleware',
    'apps.core.middleware.ExceptionMiddleware',  # Exception handling
    'django_prometheus.middleware.PrometheusAfterMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'builtins': [
                'apps.core.templatetags.custom_filters',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login URL
LOGIN_URL = '/core/login/'

# ============================================
# Email (Password reset)
# ============================================
# Email backend defaults to SMTP; set EMAIL_BACKEND to console in dev if needed.
EMAIL_BACKEND = _env('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = _env('EMAIL_HOST', default='smtp.qq.com')
EMAIL_PORT = _env('EMAIL_PORT', default=587, cast=int)
EMAIL_HOST_USER = _env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = _env('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = _env('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_USE_SSL = _env('EMAIL_USE_SSL', default=False, cast=bool)
DEFAULT_FROM_EMAIL = _env('DEFAULT_FROM_EMAIL', default='no-reply@example.com')

# Password reset email host override (useful for dev when host is 0.0.0.0)
PASSWORD_RESET_DOMAIN = _env('PASSWORD_RESET_DOMAIN', default=None)
PASSWORD_RESET_PROTOCOL = _env('PASSWORD_RESET_PROTOCOL', default=None)

# Verification code settings
VERIFICATION_CODE_TTL_SECONDS = _env('VERIFICATION_CODE_TTL_SECONDS', default=600, cast=int)
VERIFICATION_COOLDOWN_SECONDS = _env('VERIFICATION_COOLDOWN_SECONDS', default=60, cast=int)
VERIFICATION_SEND_LIMIT_HOURLY = _env('VERIFICATION_SEND_LIMIT_HOURLY', default=5, cast=int)
VERIFICATION_SEND_LIMIT_DAILY = _env('VERIFICATION_SEND_LIMIT_DAILY', default=20, cast=int)
VERIFICATION_VERIFY_FAIL_LIMIT = _env('VERIFICATION_VERIFY_FAIL_LIMIT', default=5, cast=int)
VERIFICATION_LOCK_SECONDS = _env('VERIFICATION_LOCK_SECONDS', default=600, cast=int)
VERIFICATION_IP_LIMIT_HOURLY = _env('VERIFICATION_IP_LIMIT_HOURLY', default=20, cast=int)
VERIFICATION_REGISTER_TICKET_TTL_SECONDS = _env('VERIFICATION_REGISTER_TICKET_TTL_SECONDS', default=600, cast=int)
VERIFICATION_RESET_TOKEN_TTL_SECONDS = _env('VERIFICATION_RESET_TOKEN_TTL_SECONDS', default=600, cast=int)
VERIFICATION_DEBUG_ECHO_CODE = _env('VERIFICATION_DEBUG_ECHO_CODE', default=DEBUG, cast=bool)

# SMS settings
SMS_ENABLED = _env('SMS_ENABLED', default=True, cast=bool)
SMS_PROVIDER = _env('SMS_PROVIDER', default='CUSTOM')
SMS_TIMEOUT = _env('SMS_TIMEOUT', default=10, cast=int)

# 备份配置
BACKUP_DIR = BASE_DIR / 'backups'  # 备份文件存储目录
BACKUP_COMPRESSION = True  # 是否压缩备份文件
BACKUP_ENCRYPTION = False  # 是否加密备份文件

# ============================================
# Celery 配置
# ============================================
CELERY_BROKER_URL = 'redis://localhost:6379/0'  # 任务队列代理（可选，默认使用内存）
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'  # 结果后端（可选）
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Shanghai'
CELERY_ENABLE_UTC = True
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30分钟硬限制
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25分钟软限制
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000
BACKUP_RETENTION_DAYS = 30  # 备份保留天数，超过此天数的备份会被自动删除

# ============================================
# CORS 跨域配置
# ============================================
_DEFAULT_CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",      # Vue/React 开发服务器
    "http://localhost:8080",      # 备用前端服务器
    "http://localhost:5173",      # Vite 开发服务器
    "http://127.0.0.1:3000",
    "http://127.0.0.1:8080",
    "http://127.0.0.1:5173",
]

CORS_ALLOW_ALL_ORIGINS = _env('CORS_ALLOW_ALL_ORIGINS', default=False, cast=bool)
_cors_raw = _env('CORS_ALLOWED_ORIGINS', default=None)
if _cors_raw:
    CORS_ALLOWED_ORIGINS = [item.strip() for item in str(_cors_raw).split(',') if item.strip()]
else:
    CORS_ALLOWED_ORIGINS = _DEFAULT_CORS_ALLOWED_ORIGINS

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# ============================================
# REST Framework 配置
# ============================================
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'EXCEPTION_HANDLER': 'apps.core.middleware.custom_exception_handler',
}

# ============================================
# Spectacular API 文档配置
# ============================================
SPECTACULAR_SETTINGS = {
    'TITLE': '商场店铺智能运营管理系统 API',
    'DESCRIPTION': '完整的 RESTful API 文档',
    'VERSION': '1.0.0',
    'SERVE_PERMISSIONS': ['rest_framework.permissions.AllowAny'],
    'SERVERS': [
        {'url': 'http://localhost:8000', 'description': '本地开发服务器'},
        {'url': 'https://api.example.com', 'description': '生产服务器'},
    ],
    'CONTACT': {
        'name': '技术支持',
        'email': 'support@example.com',
    },
}

# ============================================
# 日志配置
# ============================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {name} {funcName}:{lineno} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '[{levelname}] {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'level': 'DEBUG',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 5,
            'level': 'INFO',
            'formatter': 'verbose',
        },
        'error_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'error.log',
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 5,
            'level': 'ERROR',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'apps': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'celery': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# 创建日志目录
os.makedirs(BASE_DIR / 'logs', exist_ok=True)

# ============================================
# Security settings (prod-safe, dev-friendly)
# ============================================

# Optional toggles for local pre-prod testing (default off in DEBUG)
ENABLE_SECURITY_HEADERS = _env('ENABLE_SECURITY_HEADERS', default=False, cast=bool)
FORCE_HTTPS = _env('FORCE_HTTPS', default=False, cast=bool)

# Session and CSRF defaults (safe for dev)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Strict'
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_AGE = 3600
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Strict'
CSRF_FAILURE_VIEW = 'apps.core.views.csrf_failure'

# CSRF trusted origins from env (comma-separated)
CSRF_TRUSTED_ORIGINS_RAW = _env('CSRF_TRUSTED_ORIGINS', default=None)
CSRF_TRUSTED_ORIGINS = _parse_hosts(CSRF_TRUSTED_ORIGINS_RAW)
if not CSRF_TRUSTED_ORIGINS and DEBUG:
    CSRF_TRUSTED_ORIGINS = ['http://localhost:3000', 'http://localhost:8080', 'http://localhost:5173']
if not CSRF_TRUSTED_ORIGINS and (ENV == 'production' or not DEBUG):
    raise ImproperlyConfigured(
        'CSRF_TRUSTED_ORIGINS is required in production or when DEBUG is False.'
    )

# Production-only security (or opt-in for debug testing)
if not DEBUG or ENABLE_SECURITY_HEADERS or FORCE_HTTPS:
    SECURE_SSL_REDIRECT = True if (not DEBUG or FORCE_HTTPS) else False
    SESSION_COOKIE_SECURE = True if (not DEBUG or FORCE_HTTPS) else False
    CSRF_COOKIE_SECURE = True if (not DEBUG or FORCE_HTTPS) else False

    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    SECURE_CONTENT_SECURITY_POLICY = {
        'DEFAULT_SRC': ("'self'",),
        'SCRIPT_SRC': ("'self'", "'unsafe-inline'"),
        'STYLE_SRC': ("'self'", "'unsafe-inline'"),
        'IMG_SRC': ("'self'", 'data:', 'https:'),
        'FONT_SRC': ("'self'", 'data:'),
        'CONNECT_SRC': ("'self'",),
        'FRAME_ANCESTORS': ("'none'",),
    }

    X_FRAME_OPTIONS = 'DENY'
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

# Reverse proxy header (keep single definition)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# ============================================
# 管理员和用户界面安全
# ============================================

# Django Admin 安全
ADMIN_URL = 'admin/'  # 不使用默认的 /admin/
ADMIN_USER_CHANGE_PASSWORD_REQUIRED = True  # 强制首次密码更改

# ============================================
# 备份和数据保护
# ============================================

# 备份保留策略
BACKUP_RETENTION_DAYS = config('BACKUP_RETENTION_DAYS', default=30, cast=int)
BACKUP_COMPRESSION = config('BACKUP_COMPRESSION', default=True, cast=bool)
BACKUP_ENCRYPTION = config('BACKUP_ENCRYPTION', default=False, cast=bool)
_backup_allowed_dirs = config('BACKUP_ALLOWED_DIRS', default=str(BACKUP_DIR))
BACKUP_ALLOWED_DIRS = [item.strip() for item in str(_backup_allowed_dirs).split(',') if item.strip()]

# ============================================
# 错误处理和日志记录
# ============================================

# 注：错误处理程序在 config/urls.py 中配置

# ============================================
# Sentry 错误追踪配置
# ============================================

SENTRY_DSN = config('SENTRY_DSN', default=None)
SENTRY_ENABLED = SENTRY_DSN is not None and not DEBUG

if SENTRY_ENABLED:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    from sentry_sdk.integrations.logging import LoggingIntegration
    from sentry_sdk.integrations.celery import CeleryIntegration
    from sentry_sdk.integrations.redis import RedisIntegration
    
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[
            DjangoIntegration(),
            LoggingIntegration(
                level=logging.INFO,        # 捕获 INFO 级别及以上的日志
                event_level=logging.ERROR  # 仅报告 ERROR 级别的日志事件
            ),
            CeleryIntegration(),
            RedisIntegration(),
        ],
        
        # 性能监控配置
        traces_sample_rate=config('SENTRY_TRACES_SAMPLE_RATE', default=0.1, cast=float),
        
        # 错误采样配置
        sample_rate=config('SENTRY_SAMPLE_RATE', default=1.0, cast=float),
        
        # 环境标识
        environment=config('ENVIRONMENT', default='production'),
        
        # 发送内容配置
        attach_stacktrace=True,  # 附加堆栈跟踪到消息事件
        include_local_variables=False,  # 不在生产环境暴露本地变量
        
        # 排除不需要报告的错误
        ignore_errors=[
            'KeyboardInterrupt',
            'SystemExit',
            'django.http.response.Http404',
        ],
        
        # 自定义事件处理器
        before_send=lambda event, hint: event if not DEBUG else None,
        
        # 额外的上下文配置
        release=config('RELEASE', default=None),
        max_breadcrumbs=50,
        with_locals=False,
    )
    
    # 在日志中标记已初始化
    logging.getLogger(__name__).info(
        f'Sentry 已初始化，DSN: {SENTRY_DSN[:50]}..., 环境: {config("ENVIRONMENT", default="production")}'
    )

# ============================================
# Observability settings
# ============================================
METRICS_ALLOW_ALL = _env('METRICS_ALLOW_ALL', default=DEBUG, cast=bool)
METRICS_ALLOWED_IPS_RAW = _env('METRICS_ALLOWED_IPS', default=None)
METRICS_ALLOWED_IPS = _parse_hosts(METRICS_ALLOWED_IPS_RAW)
METRICS_TOKEN = _env('METRICS_TOKEN', default=None)

# ============================================
# Data governance feature flags
# ============================================
ENABLE_DATA_QUALITY_CHECK = _env('ENABLE_DATA_QUALITY_CHECK', default=False, cast=bool)
ENABLE_IDEMPOTENCY = _env('ENABLE_IDEMPOTENCY', default=False, cast=bool)
ENABLE_JOB_LOCK = _env('ENABLE_JOB_LOCK', default=False, cast=bool)
ENABLE_OFFLINE_AGG = _env('ENABLE_OFFLINE_AGG', default=False, cast=bool)
