# Generated by Django 6.0.1 on 2026-01-16 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='模板名称')),
                ('type', models.CharField(choices=[('SYSTEM', '系统消息'), ('SMS', '短信'), ('EMAIL', '邮件'), ('PUSH', '推送消息')], default='SYSTEM', max_length=20, verbose_name='通知类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容模板')),
                ('variables', models.CharField(blank=True, help_text='示例: shop_name,contract_id,amount', max_length=500, null=True, verbose_name='模板变量')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '通知模板',
                'verbose_name_plural': '通知模板',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_system_notification', models.BooleanField(default=True, verbose_name='启用系统消息')),
                ('enable_sms_notification', models.BooleanField(default=True, verbose_name='启用短信通知')),
                ('enable_email_notification', models.BooleanField(default=False, verbose_name='启用邮件通知')),
                ('sms_enabled_hours', models.CharField(default='09:00-21:00', help_text='示例: 09:00-21:00 表示仅9点到21点发送短信', max_length=50, verbose_name='短信启用时间')),
                ('notify_contract_events', models.BooleanField(default=True, verbose_name='合同事件通知')),
                ('notify_payment_events', models.BooleanField(default=True, verbose_name='支付事件通知')),
                ('notify_maintenance_events', models.BooleanField(default=True, verbose_name='维修事件通知')),
                ('notify_activity_events', models.BooleanField(default=False, verbose_name='活动事件通知')),
                ('payment_reminder_days', models.PositiveIntegerField(default=3, help_text='在支付截止前多少天发送提醒，默认3天', verbose_name='提前提醒天数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '通知偏好',
                'verbose_name_plural': '通知偏好',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('CONTRACT_SUBMITTED', '合同提交审核'), ('CONTRACT_APPROVED', '合同已批准'), ('CONTRACT_REJECTED', '合同已拒绝'), ('PAYMENT_REMINDER', '支付提醒'), ('PAYMENT_OVERDUE', '支付逾期'), ('RENEWAL_REMINDER', '续签提醒'), ('MAINTENANCE_REQUEST', '维修请求'), ('ACTIVITY_REQUEST', '活动申请'), ('SYSTEM_ALERT', '系统告警')], default='SYSTEM_ALERT', max_length=50, verbose_name='通知类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('related_model', models.CharField(blank=True, help_text='示例: Contract, FinanceRecord', max_length=50, null=True, verbose_name='关联业务模型')),
                ('related_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='关联业务对象ID')),
                ('status', models.CharField(choices=[('PENDING', '待发送'), ('SENT', '已发送'), ('FAILED', '发送失败'), ('READ', '已读')], default='PENDING', max_length=20, verbose_name='状态')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='已读时间')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('failed_reason', models.TextField(blank=True, null=True, verbose_name='失败原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='收件人')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notification.notificationtemplate', verbose_name='使用的模板')),
            ],
            options={
                'verbose_name': '通知消息',
                'verbose_name_plural': '通知消息',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='收件手机号')),
                ('content', models.TextField(verbose_name='短信内容')),
                ('status', models.CharField(choices=[('PENDING', '待发送'), ('SENT', '已发送'), ('FAILED', '发送失败'), ('DELIVERED', '已送达')], default='PENDING', max_length=20, verbose_name='状态')),
                ('provider', models.CharField(blank=True, help_text='示例: ALIYUN, TENCENT, CUSTOM', max_length=50, null=True, verbose_name='短信服务商')),
                ('provider_msg_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='服务商消息ID')),
                ('related_model', models.CharField(blank=True, max_length=50, null=True, verbose_name='关联业务模型')),
                ('related_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='关联业务对象ID')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='送达时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('notification', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_record', to='notification.notification', verbose_name='关联通知')),
            ],
            options={
                'verbose_name': '短信记录',
                'verbose_name_plural': '短信记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a95ed4_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status', '-created_at'], name='notificatio_status_bc3d30_idx'),
        ),
        migrations.AddIndex(
            model_name='smsrecord',
            index=models.Index(fields=['status', '-created_at'], name='notificatio_status_7a0bca_idx'),
        ),
        migrations.AddIndex(
            model_name='smsrecord',
            index=models.Index(fields=['phone_number', '-created_at'], name='notificatio_phone_n_34727d_idx'),
        ),
    ]
