# Generated by Django 6.0.1 on 2026-01-10 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0004_contract_payment_cycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='设备的唯一标识符', max_length=100, unique=True, verbose_name='设备ID')),
                ('device_type', models.CharField(choices=[('FOOT_TRAFFIC', '客流统计仪'), ('POS_MACHINE', 'POS机'), ('ENVIRONMENT_SENSOR', '环境传感器'), ('OTHER', '其他设备')], help_text='设备的类型', max_length=30, verbose_name='设备类型')),
                ('device_name', models.CharField(help_text='设备的名称', max_length=100, verbose_name='设备名称')),
                ('status', models.CharField(choices=[('ONLINE', '在线'), ('OFFLINE', '离线'), ('MAINTENANCE', '维护中')], default='OFFLINE', help_text='设备的当前状态', max_length=20, verbose_name='设备状态')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='设备的IP地址', null=True, verbose_name='IP地址')),
                ('mac_address', models.CharField(blank=True, help_text='设备的MAC地址', max_length=50, null=True, verbose_name='MAC地址')),
                ('api_key', models.CharField(blank=True, help_text='设备调用API的密钥', max_length=200, null=True, verbose_name='API密钥')),
                ('last_active_at', models.DateTimeField(blank=True, help_text='设备最后一次活跃的时间', null=True, verbose_name='最后活跃时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='设备创建的时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='设备信息更新的时间', verbose_name='更新时间')),
                ('shop', models.ForeignKey(help_text='设备所属的店铺', on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='store.shop', verbose_name='关联店铺')),
            ],
            options={
                'verbose_name': '智能设备',
                'verbose_name_plural': '智能设备',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(help_text='数据的类型，如客流量、销售额等', max_length=50, verbose_name='数据类型')),
                ('value', models.DecimalField(decimal_places=2, help_text='数据的具体值', max_digits=15, verbose_name='数据值')),
                ('data_time', models.DateTimeField(help_text='数据产生的时间', verbose_name='数据时间')),
                ('collected_at', models.DateTimeField(auto_now_add=True, help_text='数据被系统采集的时间', verbose_name='采集时间')),
                ('metadata', models.JSONField(blank=True, help_text='与数据相关的额外信息', null=True, verbose_name='额外信息')),
                ('device', models.ForeignKey(help_text='数据来源的设备', on_delete=django.db.models.deletion.PROTECT, related_name='device_data', to='operations.device', verbose_name='关联设备')),
                ('shop', models.ForeignKey(help_text='数据所属的店铺', on_delete=django.db.models.deletion.PROTECT, related_name='device_data', to='store.shop', verbose_name='关联店铺')),
            ],
            options={
                'verbose_name': '设备数据',
                'verbose_name_plural': '设备数据',
                'ordering': ['-data_time'],
                'indexes': [models.Index(fields=['shop', 'data_type', 'data_time'], name='operations__shop_id_0228a2_idx'), models.Index(fields=['device', 'data_time'], name='operations__device__714f16_idx')],
            },
        ),
        migrations.CreateModel(
            name='ManualOperationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_date', models.DateField(help_text='数据对应的日期', verbose_name='数据日期')),
                ('foot_traffic', models.IntegerField(blank=True, help_text='店铺的客流量', null=True, verbose_name='客流量')),
                ('sales_amount', models.DecimalField(blank=True, decimal_places=2, help_text='店铺的销售额', max_digits=15, null=True, verbose_name='销售额')),
                ('transaction_count', models.IntegerField(blank=True, help_text='店铺的交易笔数', null=True, verbose_name='交易笔数')),
                ('average_transaction_value', models.DecimalField(blank=True, decimal_places=2, help_text='店铺的客单价', max_digits=10, null=True, verbose_name='客单价')),
                ('other_data', models.JSONField(blank=True, help_text='其他运营相关数据', null=True, verbose_name='其他数据')),
                ('uploaded_by', models.CharField(help_text='数据上传人', max_length=100, verbose_name='上传人')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='数据上传的时间', verbose_name='上传时间')),
                ('remarks', models.TextField(blank=True, help_text='数据的备注信息', null=True, verbose_name='备注')),
                ('shop', models.ForeignKey(help_text='数据所属的店铺', on_delete=django.db.models.deletion.PROTECT, related_name='manual_operation_data', to='store.shop', verbose_name='关联店铺')),
            ],
            options={
                'verbose_name': '手动运营数据',
                'verbose_name_plural': '手动运营数据',
                'ordering': ['-data_date'],
                'unique_together': {('shop', 'data_date')},
            },
        ),
        migrations.CreateModel(
            name='OperationAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_period', models.CharField(help_text='分析的时间周期，如日、周、月等', max_length=20, verbose_name='分析周期')),
                ('period_start', models.DateTimeField(help_text='分析周期的开始时间', verbose_name='周期开始时间')),
                ('period_end', models.DateTimeField(help_text='分析周期的结束时间', verbose_name='周期结束时间')),
                ('total_foot_traffic', models.IntegerField(help_text='分析周期内的总客流量', verbose_name='总客流量')),
                ('average_daily_foot_traffic', models.DecimalField(decimal_places=2, help_text='分析周期内的日均客流量', max_digits=10, verbose_name='日均客流量')),
                ('total_sales', models.DecimalField(decimal_places=2, help_text='分析周期内的总销售额', max_digits=15, verbose_name='总销售额')),
                ('average_daily_sales', models.DecimalField(decimal_places=2, help_text='分析周期内的日均销售额', max_digits=15, verbose_name='日均销售额')),
                ('average_transaction_value', models.DecimalField(decimal_places=2, help_text='分析周期内的客单价', max_digits=10, verbose_name='客单价')),
                ('conversion_rate', models.DecimalField(decimal_places=4, help_text='分析周期内的转化率', max_digits=8, verbose_name='转化率')),
                ('sales_growth_rate', models.DecimalField(blank=True, decimal_places=4, help_text='与去年同期相比的销售额增长率', max_digits=8, null=True, verbose_name='销售额增长率')),
                ('foot_traffic_growth_rate', models.DecimalField(blank=True, decimal_places=4, help_text='与去年同期相比的客流量增长率', max_digits=8, null=True, verbose_name='客流量增长率')),
                ('analysis_result', models.JSONField(blank=True, help_text='详细的分析结果数据', null=True, verbose_name='分析结果')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True, help_text='分析执行的时间', verbose_name='分析时间')),
                ('shop', models.ForeignKey(help_text='分析结果所属的店铺', on_delete=django.db.models.deletion.PROTECT, related_name='operation_analyses', to='store.shop', verbose_name='关联店铺')),
            ],
            options={
                'verbose_name': '运营分析结果',
                'verbose_name_plural': '运营分析结果',
                'ordering': ['-period_start'],
                'unique_together': {('shop', 'analysis_period', 'period_start')},
            },
        ),
    ]
