# Generated by Django 6.0.1 on 2026-01-15 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0004_contract_payment_cycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(help_text='关联的模型类型', max_length=100, verbose_name='模型类型')),
                ('object_id', models.IntegerField(help_text='关联的对象ID', verbose_name='对象ID')),
                ('action', models.CharField(choices=[('CREATE', '创建'), ('UPDATE', '更新'), ('ASSIGN', '指派'), ('APPROVE', '批准'), ('REJECT', '拒绝'), ('COMPLETE', '完成'), ('CANCEL', '取消'), ('COMMENT', '评论')], help_text='操作类型', max_length=20, verbose_name='操作类型')),
                ('description', models.TextField(help_text='操作描述和详情', verbose_name='描述')),
                ('operator', models.CharField(help_text='执行操作的人员', max_length=100, verbose_name='操作人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '流程日志',
                'verbose_name_plural': '流程日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='活动申请标题', max_length=200, verbose_name='标题')),
                ('description', models.TextField(help_text='活动申请详细描述', verbose_name='描述')),
                ('activity_type', models.CharField(choices=[('PROMOTION', '促销活动'), ('ADVERTISING', '广告投放'), ('EVENT', '专题活动'), ('OTHER', '其他')], default='OTHER', help_text='活动类型', max_length=20, verbose_name='活动类型')),
                ('start_date', models.DateTimeField(help_text='活动开始日期和时间', verbose_name='开始日期')),
                ('end_date', models.DateTimeField(help_text='活动结束日期和时间', verbose_name='结束日期')),
                ('location', models.CharField(help_text='活动场地位置', max_length=200, verbose_name='场地位置')),
                ('participants', models.IntegerField(help_text='预计参与活动的人数', verbose_name='预计参与人数')),
                ('status', models.CharField(choices=[('PENDING', '待审核'), ('APPROVED', '已批准'), ('REJECTED', '已拒绝'), ('CANCELLED', '已取消')], default='PENDING', help_text='活动申请状态', max_length=20, verbose_name='状态')),
                ('reviewer', models.CharField(blank=True, help_text='审核该申请的人员', max_length=100, null=True, verbose_name='审核人员')),
                ('review_comments', models.TextField(blank=True, help_text='审核意见和备注', null=True, verbose_name='审核意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('shop', models.ForeignKey(help_text='提交申请的店铺', on_delete=django.db.models.deletion.CASCADE, related_name='activity_applications', to='store.shop', verbose_name='店铺')),
            ],
            options={
                'verbose_name': '活动申请',
                'verbose_name_plural': '活动申请',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='维修请求标题', max_length=200, verbose_name='标题')),
                ('description', models.TextField(help_text='维修请求详细描述', verbose_name='描述')),
                ('request_type', models.CharField(choices=[('WATER', '水电故障'), ('EQUIPMENT', '设备维修'), ('FACILITY', '设施维护'), ('OTHER', '其他')], default='OTHER', help_text='维修请求类型', max_length=20, verbose_name='请求类型')),
                ('priority', models.CharField(choices=[('LOW', '低'), ('MEDIUM', '中'), ('HIGH', '高'), ('URGENT', '紧急')], default='MEDIUM', help_text='维修请求优先级', max_length=20, verbose_name='优先级')),
                ('status', models.CharField(choices=[('PENDING', '待处理'), ('ASSIGNED', '已指派'), ('IN_PROGRESS', '处理中'), ('COMPLETED', '已完成'), ('CANCELLED', '已取消')], default='PENDING', help_text='维修请求状态', max_length=20, verbose_name='状态')),
                ('assigned_to', models.CharField(blank=True, help_text='处理该请求的人员', max_length=100, null=True, verbose_name='指派人员')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, help_text='预估维修费用', max_digits=8, null=True, verbose_name='预估费用')),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, help_text='实际维修费用', max_digits=8, null=True, verbose_name='实际费用')),
                ('completion_date', models.DateField(blank=True, help_text='维修完成日期', null=True, verbose_name='完成日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('shop', models.ForeignKey(help_text='提交请求的店铺', on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='store.shop', verbose_name='店铺')),
            ],
            options={
                'verbose_name': '维修请求',
                'verbose_name_plural': '维修请求',
                'ordering': ['-created_at'],
            },
        ),
    ]
