# Generated by Django 6.0.1 on 2026-01-15 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0004_contract_payment_cycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('SHOP', '入驻店铺'), ('OPERATION', '商场运营专员'), ('FINANCE', '财务管理员'), ('MANAGEMENT', '商场管理层'), ('ADMIN', '超级管理员')], help_text='系统预定义的角色类型', max_length=20, unique=True, verbose_name='角色类型')),
                ('name', models.CharField(help_text='角色的显示名称', max_length=50, verbose_name='角色名称')),
                ('description', models.TextField(blank=True, help_text='角色的详细描述', null=True, verbose_name='角色描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'ordering': ['role_type'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, help_text='用户的联系电话', max_length=20, null=True, verbose_name='联系电话')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('role', models.ForeignKey(help_text='用户所属的角色', on_delete=django.db.models.deletion.PROTECT, to='user_management.role', verbose_name='角色')),
                ('shop', models.ForeignKey(blank=True, help_text='仅入驻店铺角色需要关联具体店铺', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='store.shop', verbose_name='关联店铺')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户配置文件',
                'verbose_name_plural': '用户配置文件',
                'ordering': ['user__username'],
            },
        ),
    ]
