# Generated by Django 6.0.1 on 2026-01-19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("user_management", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ObjectPermissionGrant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.PositiveBigIntegerField(verbose_name="Object ID")),
                ("action", models.CharField(choices=[("view", "View"), ("edit", "Edit"), ("approve", "Approve"), ("delete", "Delete")], max_length=20, verbose_name="Action")),
                ("scope", models.CharField(blank=True, help_text="Optional scope hint (region/shop/contract).", max_length=30, null=True, verbose_name="Scope")),
                ("valid_from", models.DateTimeField(default=django.utils.timezone.now, verbose_name="Valid From")),
                ("valid_until", models.DateTimeField(blank=True, null=True, verbose_name="Valid Until")),
                ("reason", models.TextField(blank=True, help_text="Reason or remark for the grant.", null=True, verbose_name="Reason")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("content_type", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype", verbose_name="Content Type")),
                ("grantee_role", models.ForeignKey(blank=True, help_text="Role that receives the permission grant.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name="object_permission_grants", to="user_management.role", verbose_name="Grantee Role")),
                ("grantee_user", models.ForeignKey(blank=True, help_text="User who receives the permission grant.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name="object_permission_grants", to=settings.AUTH_USER_MODEL, verbose_name="Grantee User")),
                ("granted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="granted_object_permissions", to=settings.AUTH_USER_MODEL, verbose_name="Granted By")),
            ],
            options={
                "verbose_name": "Object Permission Grant",
                "verbose_name_plural": "Object Permission Grants",
            },
        ),
        migrations.CreateModel(
            name="ApprovalRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.PositiveBigIntegerField(verbose_name="Object ID")),
                ("action", models.CharField(choices=[("approve_contract", "Approve Contract"), ("terminate_contract", "Terminate Contract"), ("finance_confirm", "Finance Confirm"), ("shop_status_change", "Shop Status Change")], max_length=50, verbose_name="Action")),
                ("approved_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="Approved At")),
                ("comment", models.TextField(blank=True, null=True, verbose_name="Comment")),
                ("signature_hash", models.CharField(blank=True, max_length=64, null=True, verbose_name="Signature Hash")),
                ("request_snapshot", models.JSONField(blank=True, null=True, verbose_name="Request Snapshot")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("approved_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="approval_records", to=settings.AUTH_USER_MODEL, verbose_name="Approved By")),
                ("content_type", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype", verbose_name="Content Type")),
            ],
            options={
                "verbose_name": "Approval Record",
                "verbose_name_plural": "Approval Records",
            },
        ),
        migrations.AddIndex(
            model_name="objectpermissiongrant",
            index=models.Index(fields=["content_type", "object_id", "action"], name="user_manage_content_8d9a61_idx"),
        ),
        migrations.AddIndex(
            model_name="objectpermissiongrant",
            index=models.Index(fields=["grantee_user", "action"], name="user_manage_grantee_2ecaae_idx"),
        ),
        migrations.AddIndex(
            model_name="objectpermissiongrant",
            index=models.Index(fields=["grantee_role", "action"], name="user_manage_grantee_9b7a3f_idx"),
        ),
        migrations.AddIndex(
            model_name="objectpermissiongrant",
            index=models.Index(fields=["valid_from", "valid_until"], name="user_manage_valid_f_6f2a0b_idx"),
        ),
        migrations.AddConstraint(
            model_name="objectpermissiongrant",
            constraint=models.CheckConstraint(check=models.Q(("grantee_user__isnull", False), ("grantee_role__isnull", False), _connector="OR"), name="object_permission_grant_has_grantee"),
        ),
        migrations.AddIndex(
            model_name="approvalrecord",
            index=models.Index(fields=["content_type", "object_id", "action"], name="user_manage_content_7b2ad5_idx"),
        ),
        migrations.AddIndex(
            model_name="approvalrecord",
            index=models.Index(fields=["approved_by", "approved_at"], name="user_manage_approved_f1c2da_idx"),
        ),
    ]
