# Generated by Django 5.2.10 on 2026-02-07 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_store_contract_tenant__d3a2b1_idx_store_contr_tenant__c6abb3_idx_and_more'),
        ('tenants', '0003_rename_tenants_org_tenant__c22241_idx_tenants_org_tenant__614b8d_idx_and_more'),
        ('user_management', '0008_shop_binding_attachments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopbindingattachment',
            options={'ordering': ['-created_at'], 'verbose_name': '??????', 'verbose_name_plural': '??????'},
        ),
        migrations.RenameIndex(
            model_name='approvalrecord',
            new_name='user_manage_content_97686f_idx',
            old_name='user_manage_content_7b2ad5_idx',
        ),
        migrations.RenameIndex(
            model_name='approvalrecord',
            new_name='user_manage_approve_9b11fe_idx',
            old_name='user_manage_approved_f1c2da_idx',
        ),
        migrations.RenameIndex(
            model_name='objectpermissiongrant',
            new_name='user_manage_content_703b59_idx',
            old_name='user_manage_content_8d9a61_idx',
        ),
        migrations.RenameIndex(
            model_name='objectpermissiongrant',
            new_name='user_manage_grantee_92b10b_idx',
            old_name='user_manage_grantee_2ecaae_idx',
        ),
        migrations.RenameIndex(
            model_name='objectpermissiongrant',
            new_name='user_manage_grantee_4b81af_idx',
            old_name='user_manage_grantee_9b7a3f_idx',
        ),
        migrations.RenameIndex(
            model_name='objectpermissiongrant',
            new_name='user_manage_valid_f_57f7ff_idx',
            old_name='user_manage_valid_f_6f2a0b_idx',
        ),
        migrations.AddField(
            model_name='shopbindingrequest',
            name='previous_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resubmissions', to='user_management.shopbindingrequest', verbose_name='上一轮申请'),
        ),
        migrations.AlterField(
            model_name='approvalrecord',
            name='action',
            field=models.CharField(choices=[('approve_contract', 'Approve Contract'), ('terminate_contract', 'Terminate Contract'), ('finance_confirm', 'Finance Confirm'), ('shop_status_change', 'Shop Status Change'), ('shop_binding_approve', 'Shop Binding Approve'), ('shop_binding_reject', 'Shop Binding Reject')], max_length=50, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='objectpermissiongrant',
            name='action',
            field=models.CharField(choices=[('view', 'View'), ('edit', 'Edit'), ('approve', 'Approve'), ('delete', 'Delete')], help_text='Action allowed on the target object.', max_length=20, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_type',
            field=models.CharField(choices=[('SHOP', 'Shop'), ('OPERATION', 'Operation'), ('FINANCE', 'Finance'), ('MANAGEMENT', 'Management'), ('ADMIN', 'Admin')], help_text='系统预定义的角色类型', max_length=20, unique=True, verbose_name='角色类型'),
        ),
        migrations.AlterField(
            model_name='shopbindingattachment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='shopbindingattachment',
            name='file',
            field=models.FileField(upload_to='binding_attachments/%Y/%m/', verbose_name='??'),
        ),
        migrations.AlterField(
            model_name='shopbindingattachment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shopbindingattachment',
            name='mime_type',
            field=models.CharField(max_length=100, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='shopbindingattachment',
            name='original_name',
            field=models.CharField(max_length=255, verbose_name='?????'),
        ),
        migrations.AlterField(
            model_name='shopbindingattachment',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='user_management.shopbindingrequest', verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='shopbindingattachment',
            name='size',
            field=models.PositiveIntegerField(verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='shopbindingrequest',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='shopbindingrequest',
            name='approved_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='binding_requests', to='store.shop', verbose_name='??????'),
        ),
        migrations.AlterField(
            model_name='shopbindingrequest',
            name='authorization_note',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='shopbindingrequest',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='shopbindingrequest',
            name='contact_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='?????'),
        ),
        migrations.AlterField(
            model_name='shopbindingrequest',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='shopbindingrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='shopbindingrequest',
            name='identity_type',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='shopbindingrequest',
            name='industry_category',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='shopbindingrequest',
            name='mall_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='????/??/??'),
        ),
        migrations.AlterField(
            model_name='shopbindingrequest',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='??'),
        ),
        migrations.AlterField(
            model_name='shopbindingrequest',
            name='requested_shop_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='shopbindingrequest',
            name='requested_shop_name',
            field=models.CharField(max_length=120, verbose_name='??????'),
        ),
        migrations.AlterField(
            model_name='shopbindingrequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='shopbindingrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_binding_requests', to=settings.AUTH_USER_MODEL, verbose_name='???'),
        ),
        migrations.AlterField(
            model_name='shopbindingrequest',
            name='role_requested',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='shopbindingrequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', '草稿'), ('PENDING', '待审核'), ('APPROVED', '已通过'), ('REJECTED', '已拒绝'), ('WITHDRAWN', '已撤回')], default='PENDING', max_length=20, verbose_name='??'),
        ),
        migrations.AlterField(
            model_name='shopbindingrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='shopbindingrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_binding_requests', to=settings.AUTH_USER_MODEL, verbose_name='申请人'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='用户所属的租户/商场', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='tenants.tenant', verbose_name='所属租户'),
        ),
    ]
