# Generated by Django 5.2.10 on 2026-02-07 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_store_contract_tenant__d3a2b1_idx_store_contr_tenant__c6abb3_idx_and_more'),
        ('user_management', '0009_alter_shopbindingattachment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopbindingattachment',
            options={'ordering': ['-created_at'], 'verbose_name': '绑定申请附件', 'verbose_name_plural': '绑定申请附件'},
        ),
        migrations.AlterField(
            model_name='shopbindingattachment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='shopbindingattachment',
            name='file',
            field=models.FileField(upload_to='binding_attachments/%Y/%m/', verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='shopbindingattachment',
            name='mime_type',
            field=models.CharField(max_length=100, verbose_name='文件类型'),
        ),
        migrations.AlterField(
            model_name='shopbindingattachment',
            name='original_name',
            field=models.CharField(max_length=255, verbose_name='原始文件名'),
        ),
        migrations.AlterField(
            model_name='shopbindingattachment',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='user_management.shopbindingrequest', verbose_name='所属申请'),
        ),
        migrations.AlterField(
            model_name='shopbindingattachment',
            name='size',
            field=models.PositiveIntegerField(verbose_name='文件大小'),
        ),
        migrations.AlterField(
            model_name='shopbindingrequest',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='店铺地址'),
        ),
        migrations.AlterField(
            model_name='shopbindingrequest',
            name='approved_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='binding_requests', to='store.shop', verbose_name='审核通过的店铺'),
        ),
        migrations.AlterField(
            model_name='shopbindingrequest',
            name='authorization_note',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='授权说明'),
        ),
        migrations.AlterField(
            model_name='shopbindingrequest',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='联系邮箱'),
        ),
        migrations.AlterField(
            model_name='shopbindingrequest',
            name='contact_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='联系人姓名'),
        ),
        migrations.AlterField(
            model_name='shopbindingrequest',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='shopbindingrequest',
            name='identity_type',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='申请人身份'),
        ),
        migrations.AlterField(
            model_name='shopbindingrequest',
            name='industry_category',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='行业类目'),
        ),
        migrations.AlterField(
            model_name='shopbindingrequest',
            name='mall_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='商场/园区/区域'),
        ),
        migrations.AlterField(
            model_name='shopbindingrequest',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='申请说明'),
        ),
        migrations.AlterField(
            model_name='shopbindingrequest',
            name='requested_shop_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='店铺编号/ID'),
        ),
        migrations.AlterField(
            model_name='shopbindingrequest',
            name='requested_shop_name',
            field=models.CharField(max_length=120, verbose_name='申请店铺名称'),
        ),
        migrations.AlterField(
            model_name='shopbindingrequest',
            name='review_reason',
            field=models.TextField(blank=True, null=True, verbose_name='审核意见/拒绝原因'),
        ),
        migrations.AlterField(
            model_name='shopbindingrequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核时间'),
        ),
        migrations.AlterField(
            model_name='shopbindingrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_binding_requests', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
        migrations.AlterField(
            model_name='shopbindingrequest',
            name='role_requested',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='期望角色'),
        ),
        migrations.AlterField(
            model_name='shopbindingrequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', '草稿'), ('PENDING', '待审核'), ('APPROVED', '已通过'), ('REJECTED', '已拒绝'), ('WITHDRAWN', '已撤回')], default='PENDING', max_length=20, verbose_name='状态'),
        ),
    ]
